require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/facts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Fact. As you add validations to Fact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Fact.create! valid_attributes
      get facts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      fact = Fact.create! valid_attributes
      get fact_url(fact)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_fact_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      fact = Fact.create! valid_attributes
      get edit_fact_url(fact)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Fact" do
        expect {
          post facts_url, params: { fact: valid_attributes }
        }.to change(Fact, :count).by(1)
      end

      it "redirects to the created fact" do
        post facts_url, params: { fact: valid_attributes }
        expect(response).to redirect_to(fact_url(Fact.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Fact" do
        expect {
          post facts_url, params: { fact: invalid_attributes }
        }.to change(Fact, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post facts_url, params: { fact: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fact" do
        fact = Fact.create! valid_attributes
        patch fact_url(fact), params: { fact: new_attributes }
        fact.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the fact" do
        fact = Fact.create! valid_attributes
        patch fact_url(fact), params: { fact: new_attributes }
        fact.reload
        expect(response).to redirect_to(fact_url(fact))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        fact = Fact.create! valid_attributes
        patch fact_url(fact), params: { fact: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested fact" do
      fact = Fact.create! valid_attributes
      expect {
        delete fact_url(fact)
      }.to change(Fact, :count).by(-1)
    end

    it "redirects to the facts list" do
      fact = Fact.create! valid_attributes
      delete fact_url(fact)
      expect(response).to redirect_to(facts_url)
    end
  end
end
