require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/paragraphs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Paragraph. As you add validations to Paragraph, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Paragraph.create! valid_attributes
      get paragraphs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      paragraph = Paragraph.create! valid_attributes
      get paragraph_url(paragraph)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_paragraph_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      paragraph = Paragraph.create! valid_attributes
      get edit_paragraph_url(paragraph)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Paragraph" do
        expect {
          post paragraphs_url, params: { paragraph: valid_attributes }
        }.to change(Paragraph, :count).by(1)
      end

      it "redirects to the created paragraph" do
        post paragraphs_url, params: { paragraph: valid_attributes }
        expect(response).to redirect_to(paragraph_url(Paragraph.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Paragraph" do
        expect {
          post paragraphs_url, params: { paragraph: invalid_attributes }
        }.to change(Paragraph, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post paragraphs_url, params: { paragraph: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested paragraph" do
        paragraph = Paragraph.create! valid_attributes
        patch paragraph_url(paragraph), params: { paragraph: new_attributes }
        paragraph.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the paragraph" do
        paragraph = Paragraph.create! valid_attributes
        patch paragraph_url(paragraph), params: { paragraph: new_attributes }
        paragraph.reload
        expect(response).to redirect_to(paragraph_url(paragraph))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        paragraph = Paragraph.create! valid_attributes
        patch paragraph_url(paragraph), params: { paragraph: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested paragraph" do
      paragraph = Paragraph.create! valid_attributes
      expect {
        delete paragraph_url(paragraph)
      }.to change(Paragraph, :count).by(-1)
    end

    it "redirects to the paragraphs list" do
      paragraph = Paragraph.create! valid_attributes
      delete paragraph_url(paragraph)
      expect(response).to redirect_to(paragraphs_url)
    end
  end
end
